### ISSUE TITLE
Allure Reports for Bamboo - Cannot allocate memory

### ISSUE THREAD

**Issue by wiolken44** [allure-framework/allure-bamboo#60]
Hi,
We have a problem with generating allure reports. Sometimes reports are generated and sometimes the same reports are not generated because of out of memory problem.
It’s always the same error:
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000600000000, 5011144704, 0) failed; error='Cannot allocate memory' (errno=12)
It’s strange because available free memory is often about 2GB and one time reports are generated with success and another time without success. Error shows that needed about 5GB memory.
If we increase RAM, the problem will disappear, or not? We can’t increasing RAM with every Allure error about memory.
What we can do? How much RAM should be reserved for allure reports plugin?
 
Please support. 

Regards,
Wiola

**Comment by smecsia** [comment]
@wiolken44 when is this happening? Where exactly do you see the OOM error?

**Comment by wiolken44** [comment]
Hi,
OOM error is in Allure Report tab:
![image](https://user-images.githubusercontent.com/19697386/61711940-84011680-ad55-11e9-9a5e-f2a415543082.png)

Reports are generated mainly with success, but sometimes the same report does not generate and is with an OOM error, but we do not know why.

**Comment by FrostRunner** [comment]
Increase RAM on server solved our same problem.
We waas change RAM from 24 to 32 GB

**Comment by jdesulme** [comment]
We're running into this same issue as well. Although our Bamboo instance size already pretty large at a c5.9xlarge (36 CPU & 72 GB Memory). We can't really go up any higher. 


```
Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /v*********n/allure generate -o /var/vcap/packages/atlassian-bamboo/atlassian-bamboo-standalone/temp/1569865667710-1/report /v*********o/atlassian-bamboo-standalone/temp/1569865667710-0/31dbf336-d8e8-4f0e-9047-6d049f4c5f5f' returned 1 after 235ms
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000080000000, 32212254720, 0) failed; error='Cannot allocate memory' (errno=12)
```

**Comment by KarinaT** [comment]
Hello, we are facing the same issue on the Bamboo.

Our Bamboo team has tried several options, but that didn't help:

"We already **have maxed out settings with the build agents resource and JVM settings wise** and this is due to a bug on the vendor side with a plugin that appears to have been abandoned."

"Just to clarify, the memory issue is not with Bamboo itself, and instead relates to the Allure-developed plugin.  This is the challenge because Bamboo issues would be something our team could theoretically take action on - but because this is a plugin developed by an external vendor, we are limited in terms of what we are able to do here. "


Could you please take a look?

**Comment by doctormonocle** [comment]
I know this issue is super old, but I just hit it today. The problem is that the Allure plug-in re-uses the jvm options set in Bamboo's setenv.sh. So unless you have enough un-allocated memory equal to your app, you'll get this error when the report tries to generate.

**Comment by baev** [comment]
closed as stale
